"""reverting chat, room, different different changes

Revision ID: 050d970cbd31
Revises: f86d9b831a0e
Create Date: 2026-02-25 21:04:27.355826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050d970cbd31'
down_revision: Union[str, Sequence[str], None] = 'f86d9b831a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_room_chat'), 'chats', type_='unique')
    op.drop_constraint(op.f('chats_room_id_fkey'), 'chats', type_='foreignkey')
    op.drop_column('chats', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chats_room_id_fkey'), 'chats', 'rooms', ['room_id'], ['id'])
    op.create_unique_constraint(op.f('unique_room_chat'), 'chats', ['user1_id', 'user2_id', 'room_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
