"""room id with constraints in chat table

Revision ID: 0aabe1c517ff
Revises: ef9367b3646c
Create Date: 2026-02-25 19:50:54.969980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aabe1c517ff'
down_revision: Union[str, Sequence[str], None] = 'ef9367b3646c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_room_chat', 'chats', ['user1_id', 'user2_id', 'room_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_room_chat', 'chats', type_='unique')
    # ### end Alembic commands ###
