"""nullable changes

Revision ID: 78365f0f06c4
Revises: 8da147f736f6
Create Date: 2026-02-10 20:28:14.787743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78365f0f06c4'
down_revision: Union[str, Sequence[str], None] = '8da147f736f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'applicant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'rejected', name='application_status'),
               nullable=True)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room_images', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room_views', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room_views', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rooms', 'area',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'deposit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'is_furnished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('seeker', 'owner', 'both', name='user_role'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('seeker', 'owner', 'both', name='user_role'),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'is_furnished',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rooms', 'deposit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rooms', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rooms', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rooms', 'area',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rooms', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room_views', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room_views', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room_images', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'rejected', name='application_status'),
               nullable=False)
    op.alter_column('applications', 'applicant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
