"""room id in chat table

Revision ID: ef9367b3646c
Revises: c6dfe5deb30e
Create Date: 2026-02-25 19:48:59.434214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9367b3646c'
down_revision: Union[str, Sequence[str], None] = 'c6dfe5deb30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'room_id')
    # ### end Alembic commands ###
